/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ServiceRequestsObjectPageObjectPage journey");

        opaTest("Navigate to ServiceRequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheServiceRequestsList.onFilterBar().iExecuteSearch();

            Then.onTheServiceRequestsList.onTable().iCheckRows();
            When.onTheServiceRequestsList.onTable().iPressRow(0);

            Then.onTheServiceRequestsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheServiceRequestsObjectPage.iCheckNumberOfSections(5);
            When.onTheServiceRequestsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::RaiseTicket");
            Then.onTheServiceRequestsObjectPage.iCheckSection({ section: "FieldGroup::RaiseTicket" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "RequestType" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "Title" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "Description" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "Category" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "SubCategory" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "Priority" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "Impact" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "Urgency" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "SourceChannel" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::RaiseTicket" }).iCheckField({ property: "IsVIPUser" });
            When.onTheServiceRequestsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::StatusSLA");
            Then.onTheServiceRequestsObjectPage.iCheckSection({ section: "FieldGroup::StatusSLA" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::StatusSLA" }).iCheckField({ property: "Status" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::StatusSLA" }).iCheckField({ property: "AssignedTeam" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::StatusSLA" }).iCheckField({ property: "SLADeadline" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::StatusSLA" }).iCheckField({ property: "ResponseDue" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::StatusSLA" }).iCheckField({ property: "FirstResponseAt" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::StatusSLA" }).iCheckField({ property: "SLABreached" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::StatusSLA" }).iCheckField({ property: "EscalationLevel" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::StatusSLA" }).iCheckField({ property: "EscalatedAt" });
            When.onTheServiceRequestsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::Resolution");
            Then.onTheServiceRequestsObjectPage.iCheckSection({ section: "FieldGroup::Resolution" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Resolution" }).iCheckField({ property: "ResolvedAt" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Resolution" }).iCheckField({ property: "ResolutionSummary" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Resolution" }).iCheckField({ property: "RootCause" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Resolution" }).iCheckField({ property: "WorkaroundProvided" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Resolution" }).iCheckField({ property: "CustomerFeedback" });
            When.onTheServiceRequestsObjectPage.iPressSectionIconTabFilterButton("Comments::LineItem");
            Then.onTheServiceRequestsObjectPage.iCheckSection({ section: "Comments::LineItem" });
            When.onTheServiceRequestsObjectPage.iPressSectionIconTabFilterButton("FieldGroup::Assets");
            Then.onTheServiceRequestsObjectPage.iCheckSection({ section: "FieldGroup::Assets" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "AssetTag" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "AssetName" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "AssetType" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "Category" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "Brand" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "Model" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "SerialNumber" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "AssetCondition" });
            Then.onTheServiceRequestsObjectPage.onForm({ section: "FieldGroup::Assets" }).iCheckField({ property: "Status" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});