/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TicketAnalyticsObjectPageObjectPage journey");

        opaTest("Navigate to TicketAnalyticsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheTicketAnalyticsList.onFilterBar().iExecuteSearch();

            Then.onTheTicketAnalyticsList.onTable().iCheckRows();
            When.onTheTicketAnalyticsList.onTable().iPressRow(0);

            Then.onTheTicketAnalyticsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTicketAnalyticsObjectPage.iCheckNumberOfSections(3);
            When.onTheTicketAnalyticsObjectPage.iPressSectionIconTabFilterButton("ClassificationFacet");
            Then.onTheTicketAnalyticsObjectPage.iCheckSection({ section: "ClassificationFacet" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "ClassificationFacet" }).iCheckField({ property: "Priority" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "ClassificationFacet" }).iCheckField({ property: "Status" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "ClassificationFacet" }).iCheckField({ property: "RequestType" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "ClassificationFacet" }).iCheckField({ property: "Category" });
            When.onTheTicketAnalyticsObjectPage.iPressSectionIconTabFilterButton("VolumeFacet");
            Then.onTheTicketAnalyticsObjectPage.iCheckSection({ section: "VolumeFacet" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "VolumeFacet" }).iCheckField({ property: "TotalTickets" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "VolumeFacet" }).iCheckField({ property: "OpenTickets" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "VolumeFacet" }).iCheckField({ property: "CriticalTickets" });
            When.onTheTicketAnalyticsObjectPage.iPressSectionIconTabFilterButton("SLAFacet");
            Then.onTheTicketAnalyticsObjectPage.iCheckSection({ section: "SLAFacet" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "SLAFacet" }).iCheckField({ property: "BreachedTickets" });
            Then.onTheTicketAnalyticsObjectPage.onForm({ section: "SLAFacet" }).iCheckField({ property: "EscalatedTickets" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});