/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TicketAnalyticsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheTicketAnalyticsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheTicketAnalyticsList.onFilterBar().iCheckFilterField("Priority");
            Then.onTheTicketAnalyticsList.onFilterBar().iCheckFilterField("Status");
            Then.onTheTicketAnalyticsList.onFilterBar().iCheckFilterField("Request Type");
            Then.onTheTicketAnalyticsList.onFilterBar().iCheckFilterField("Category");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheTicketAnalyticsList.onTable().iCheckColumns(undefined, {"Priority":{"header":"Priority"},"Status":{"header":"Status"},"RequestType":{"header":"Request Type"},"Category":{"header":"Category"},"TotalTickets":{"header":"Total Tickets"},"BreachedTickets":{"header":"SLA Breached"},"OpenTickets":{"header":"Open Tickets"},"EscalatedTickets":{"header":"Escalated"},"CriticalTickets":{"header":"Critical"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheTicketAnalyticsList.onFilterBar().iExecuteSearch();
            
            Then.onTheTicketAnalyticsList.onTable().iCheckRows();

            When.onTheTicketAnalyticsList.onTable().iPressRow(0);
            Then.onTheTicketAnalyticsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});